version: "3.9"
services:
  receiver:
    build: 
      context: ./receiver
      dockerfile: Dockerfile
    entrypoint: flask run
    ports:
      - "8080:8080"
  pinger:
    build: 
      context: ./pinger
      dockerfile: Dockerfile
    entrypoint: flask run
    ports: 
      - "8070:8080"