FROM python:3.7-alpine
WORKDIR /receiver
ENV FLASK_APP=receiver.py
# ENV FLASK_RUN_HOST=127.0.0.1
RUN apk add --no-cache gcc musl-dev linux-headers
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 8080
COPY . .